# Generated by Django 5.2.2 on 2025-09-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('question_type', models.CharField(default='multiple_choice', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Initial Learning Assessment', max_length=200)),
                ('description', models.TextField(default='Complete this assessment to get personalized course recommendations.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('skill_points', models.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.assessmentquestion')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.assessmentquiz'),
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('skill_scores', models.JSONField(default=dict)),
                ('recommended_courses', models.JSONField(default=list)),
                ('learning_level', models.CharField(default='beginner', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.assessmentquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.studentprofile')),
            ],
        ),
    ]
